import { Link } from "react-router-dom";
import { Minus, Plus, ShoppingBag, Trash2, X } from "lucide-react";
import { useCart } from "../context/CartContext";

export default function CartDrawer() {
  const c = useCart();
  return <><button onClick={() => c.setOpen(true)} className="fixed bottom-5 right-5 z-30 rounded-full bg-masala p-4 text-white shadow-2xl md:hidden"><ShoppingBag /></button>{c.open && <div className="fixed inset-0 z-50 bg-black/40" onClick={() => c.setOpen(false)}><aside onClick={(e) => e.stopPropagation()} className="ml-auto flex h-full w-full max-w-md flex-col bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-5"><h2 className="text-xl font-black">Your Cart</h2><button className="icon-btn" onClick={() => c.setOpen(false)}><X /></button></div><div className="flex-1 space-y-4 overflow-auto p-5">{c.items.length === 0 && <p className="text-gray-500">Your cart is waiting for something delicious.</p>}{c.items.map((item) => <div key={item._id} className="flex gap-3 rounded-2xl border p-3"><img src={item.image} className="h-20 w-20 rounded-xl object-cover" /><div className="min-w-0 flex-1"><h3 className="font-black">{item.name}</h3><p className="text-sm text-gray-500">₹{item.price}</p><div className="mt-2 flex items-center gap-2"><button className="mini-btn" onClick={() => c.dec(item._id)}><Minus /></button><b>{item.quantity}</b><button className="mini-btn" onClick={() => c.inc(item._id)}><Plus /></button><button className="mini-btn ml-auto text-masala" onClick={() => c.remove(item._id)}><Trash2 /></button></div></div></div>)}</div><div className="border-t p-5"><input value={c.coupon} onChange={(e) => c.setCoupon(e.target.value)} placeholder="Coupon code" className="field mb-3" /><div className="space-y-2 text-sm"><Row label="Subtotal" value={c.subtotal} /><Row label="Delivery" value={c.deliveryFee} /><Row label="GST" value={c.tax} /><Row label="Discount" value={-c.discount} /><div className="flex justify-between border-t pt-3 text-lg font-black"><span>Total</span><span>₹{c.total}</span></div></div><Link to="/checkout" onClick={() => c.setOpen(false)} className={`btn-primary mt-5 w-full justify-center ${!c.items.length ? "pointer-events-none opacity-50" : ""}`}>Checkout</Link></div></aside></div>}</>;
}
function Row({ label, value }) { return <div className="flex justify-between"><span>{label}</span><b>₹{value}</b></div>; }
