import { Link, NavLink } from "react-router-dom";
import { Crown, LogOut, Menu, ShoppingCart, UserRound } from "lucide-react";
import { useState } from "react";
import { useAuth } from "../context/AuthContext";
import { useCart } from "../context/CartContext";

export default function Navbar() {
  const { user, isOwner, loginPhone, logout } = useAuth();
  const { items, setOpen } = useCart();
  const [phone, setPhone] = useState("");
  const [mobile, setMobile] = useState(false);
  const links = [["/", "Home"], ["/#menu", "Menu"], ["/#offers", "Offers"], ["/#contact", "Contact"], ["/orders", "Orders"]];
  const submit = (e) => { e.preventDefault(); if (phone) loginPhone(phone); };
  return <header className="sticky top-0 z-40 border-b border-gold/20 bg-royal/90 text-white shadow-royal backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4"><Link to="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full border border-gold/40 bg-gold/10 text-gold"><Crown className="h-5 w-5" /></span><span className="leading-tight"><span className="block text-xl font-black text-white">Shreeji Food</span><span className="block text-[10px] font-black uppercase tracking-[0.3em] text-gold">Online Atelier</span></span></Link><nav className="hidden items-center gap-6 text-sm font-bold md:flex">{links.map(([to, label]) => <NavLink key={label} to={to} className="text-white/75 transition hover:text-gold">{label}</NavLink>)}{isOwner && <Link className="rounded-full border border-gold/40 bg-gold/10 px-4 py-2 text-gold" to="/owner">Owner Dashboard</Link>}</nav><div className="hidden items-center gap-2 md:flex">{user ? <><span className="rounded-full border border-gold/20 bg-white/10 px-3 py-2 text-sm text-white/90"><UserRound className="mr-1 inline h-4 w-4 text-gold" />{user.phone}</span><button onClick={logout} className="icon-btn"><LogOut /></button></> : <form onSubmit={submit} className="flex rounded-full border border-gold/30 bg-white/10 p-1 backdrop-blur"><input value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="Phone login" className="w-32 bg-transparent px-3 text-sm text-white outline-none placeholder:text-white/50" /><button className="rounded-full bg-gold px-4 py-2 text-sm font-black text-royal">Login</button></form>}<button onClick={() => setOpen(true)} className="relative icon-btn"><ShoppingCart />{items.length > 0 && <b className="absolute -right-1 -top-1 grid h-5 w-5 place-items-center rounded-full bg-masala text-xs text-white">{items.length}</b>}</button></div><button className="icon-btn md:hidden" onClick={() => setMobile(!mobile)}><Menu /></button></div>{mobile && <div className="space-y-3 border-t border-gold/20 bg-royal px-4 py-4 md:hidden">{links.map(([to, label]) => <Link key={label} onClick={() => setMobile(false)} to={to} className="block font-semibold text-white/80">{label}</Link>)}{isOwner && <Link to="/owner" className="block font-semibold text-gold">Owner Dashboard</Link>}<form onSubmit={submit} className="flex gap-2"><input value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="Phone number" className="min-w-0 flex-1 rounded-xl border border-gold/30 bg-white/10 px-3 py-2 text-white" />{user ? <button type="button" onClick={logout} className="btn-secondary">Logout</button> : <button className="btn-primary">Login</button>}</form><button onClick={() => setOpen(true)} className="btn-primary w-full justify-center">Cart ({items.length})</button></div>}</header>;
}
