import { useEffect, useMemo, useState } from "react";
import toast from "react-hot-toast";
import api from "../api/axios";
import { useSocket } from "../context/SocketContext";
import { getLocalOrders, updateLocalOrder } from "../utils/localStore";

const statuses = ["Pending", "Accepted", "Preparing", "Out for Delivery", "Delivered", "Cancelled"];

export default function OwnerDashboard({ data, reload }) {
  const { socket } = useSocket();
  const [orders, setOrders] = useState([]);
  const [categories, setCategories] = useState(data.categories || []);
  const loadOrders = () => api.get("/api/orders/all").then((r) => setOrders(r.data.length ? r.data : getLocalOrders())).catch(() => setOrders(getLocalOrders()));
  useEffect(() => { loadOrders(); }, []);
  useEffect(() => setCategories(data.categories || []), [data.categories]);
  useEffect(() => { if (!socket) return; const onNew = () => { toast.success("New order received"); try { new Audio("data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAESsAACJWAAACABAAZGF0YQAAAAA=").play(); } catch { /* notification audio is best effort */ } loadOrders(); }; socket.on("order:new", onNew); socket.on("order:statusUpdated", loadOrders); socket.on("payment:success", loadOrders); return () => { socket.off("order:new", onNew); socket.off("order:statusUpdated", loadOrders); socket.off("payment:success", loadOrders); }; }, [socket]);
  const stats = useMemo(() => ({ sales: orders.filter((o) => o.paymentStatus === "paid").reduce((s, o) => s + o.total, 0), pending: orders.filter((o) => o.status === "Pending").length, today: orders.filter((o) => new Date(o.createdAt).toDateString() === new Date().toDateString()).length }), [orders]);
  const updateStatus = async (id, status) => { try { await api.put(`/api/orders/${id}/status`, { status }); } catch { updateLocalOrder(id, { status }); } loadOrders(); };
  const updatePayment = async (order, paymentStatus) => { try { await api.put(`/api/orders/${order._id}/payment-status`, { paymentStatus, paymentId: order.paymentId }); } catch { updateLocalOrder(order._id, { paymentStatus, paymentId: order.paymentId }); } loadOrders(); };
  const addCategory = async () => { const name = prompt("Category name"); if (name) { try { await api.post("/api/categories", { name }); reload(); } catch { toast.error("Backend needed to save categories"); } } };
  const updateCategory = async (id, name) => { try { await api.put(`/api/categories/${id}`, { name }); reload(); } catch { toast.error("Backend needed to save categories"); } };
  const deleteCategory = async (id) => { try { await api.delete(`/api/categories/${id}`); reload(); } catch { toast.error("Backend needed to delete categories"); } };
  return <section className="mx-auto max-w-7xl px-4 py-10"><p className="section-kicker">Owner only</p><h1 className="section-title mb-8">Shreeji Command Center</h1><div className="grid gap-4 md:grid-cols-4"><Stat label="Total sales" value={`₹${stats.sales}`} /><Stat label="Today’s orders" value={stats.today} /><Stat label="Pending" value={stats.pending} /><Stat label="Menu items" value={data.menu.length} /></div><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_360px]"><div className="rounded-3xl bg-white p-5 shadow-premium"><h2 className="mb-4 text-2xl font-black">Live Orders</h2><div className="space-y-4">{orders.map((o) => <article key={o._id} className="rounded-2xl border p-4"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-black">{o.customerName} · {o.phone}</h3><p className="text-sm text-gray-500">{o.address}</p><p className="text-sm text-gray-500">{o.items.map((i) => `${i.quantity}x ${i.name}`).join(", ")}</p></div><div className="text-right"><p className="text-xl font-black text-masala">₹{o.total}</p><p className="text-xs font-bold text-chutney">{o.paymentStatus} {o.paymentId && `· ${o.paymentId}`}</p></div></div><div className="mt-3 grid gap-3 md:grid-cols-2"><select className="field" value={o.status} onChange={(e) => updateStatus(o._id, e.target.value)}>{statuses.map((s) => <option key={s}>{s}</option>)}</select><select className="field" value={o.paymentStatus} onChange={(e) => updatePayment(o, e.target.value)}>{["pending","submitted","paid","failed"].map((s) => <option key={s}>{s}</option>)}</select></div></article>)}</div></div><aside className="space-y-6"><div className="rounded-3xl bg-white p-5 shadow-premium"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-black">Categories</h2><button className="btn-secondary" onClick={addCategory}>Add</button></div><div className="space-y-2">{categories.map((c) => <div key={c._id} className="flex gap-2"><input className="field" defaultValue={c.name} onBlur={(e) => e.target.value !== c.name && updateCategory(c._id, e.target.value)} /><button className="rounded-xl bg-red-50 px-3 font-bold text-masala" onClick={() => deleteCategory(c._id)}>Delete</button></div>)}</div></div><div className="rounded-3xl bg-white p-5 shadow-premium"><h2 className="text-xl font-black">Content Editor</h2><p className="mt-2 text-sm leading-6 text-gray-600">Double-click hero, offer, contact, menu names, descriptions and prices anywhere on the public site. Changes are saved to GitHub JSON data files and broadcast live.</p></div></aside></div></section>;
}
function Stat({ label, value }) { return <div className="rounded-3xl bg-white p-5 shadow-sm"><p className="text-sm font-bold text-gray-500">{label}</p><p className="mt-2 text-3xl font-black text-masala">{value}</p></div>; }
